package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final

/**
 * Image generated by hbm2java
 */
public class Image{

	private ImageId id;
	private Information information;

	public Image() {
	}

	public Image(ImageId id, Information information) {
		this.id = id;
		this.information = information;
	}

	public ImageId getId() {
		return this.id;
	}

	public void setId(ImageId id) {
		this.id = id;
	}

	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}

}
