package entity;
// Generated Mar 26, 2017 12:44:17 PM by Hibernate Tools 4.3.1.Final

/**
 * RatingId generated by hbm2java
 */
public class RatingId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int infor;
	private int users;

	public RatingId() {
	}

	public RatingId(int infor, int users) {
		this.infor = infor;
		this.users = users;
	}

	public int getInfor() {
		return this.infor;
	}

	public void setInfor(int infor) {
		this.infor = infor;
	}

	public int getUsers() {
		return this.users;
	}

	public void setUsers(int users) {
		this.users = users;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RatingId))
			return false;
		RatingId castOther = (RatingId) other;

		return (this.getInfor() == castOther.getInfor()) && (this.getUsers() == castOther.getUsers());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInfor();
		result = 37 * result + this.getUsers();
		return result;
	}

}
