package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
public class Room {

	private int id;
	private Information information;
	private String type;
	private String detail;
	private String quanlity;
	private int maxpeople;
	private int price;
	private String Image;
	public String getImage() {
		return Image;
	}

	public void setImage(String image) {
		Image = image;
	}

	private Set<Booking> bookings = new HashSet<Booking>(0);


	public Room() {
	}

	public Room(int id, Information information, String type, int maxpeople, int price) {
		this.id = id;
		this.information = information;
		this.type = type;
		this.maxpeople = maxpeople;
		this.price = price;
	}

	public Room(int id, Information information, String type, String detail, String quanlity,
			int maxpeople, int price, Set<Booking> bookings) {
		this.id = id;
		this.information = information;
		this.type = type;
		this.detail = detail;
		this.quanlity = quanlity;
		this.maxpeople = maxpeople;
		this.price = price;
		this.bookings = bookings;

	}
	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getQuanlity() {
		return this.quanlity;
	}

	public void setQuanlity(String quanlity) {
		this.quanlity = quanlity;
	}
	public int getMaxpeople() {
		return this.maxpeople;
	}

	public void setMaxpeople(int maxpeople) {
		this.maxpeople = maxpeople;
	}

	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

	
}
