package entity;
// Generated Mar 26, 2017 12:44:17 PM by Hibernate Tools 4.3.1.Final

/**
 * Serviceinfor generated by hbm2java
 */
public class Serviceinfor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ServiceinforId id;
	private Information information;
	private Service service;

	public Serviceinfor() {
	}

	public Serviceinfor(ServiceinforId id, Information information, Service service) {
		this.id = id;
		this.information = information;
		this.service = service;
	}

	public ServiceinforId getId() {
		return this.id;
	}

	public void setId(ServiceinforId id) {
		this.id = id;
	}

	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}

	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

}
