package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;

/**
 * Users generated by hbm2java
 */
public class Users {

	private int id;
	private String fullname;
	private String phone;
	private String email;
	private String password;
	private int point;
	private List<Booking >bookings = new ArrayList<Booking>();
	
	public Users() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Users(int id, String fullname, String phone, String email, String password, int point,
			List<Booking> bookings) {
		super();
		this.id = id;
		this.fullname = fullname;
		this.phone = phone;
		this.email = email;
		this.password = password;
		this.point = point;
		this.bookings = bookings;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getFullname() {
		return fullname;
	}
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public int getPoint() {
		return point;
	}
	public void setPoint(int point) {
		this.point = point;
	}
	public List<Booking> getBookings() {
		return bookings;
	}
	public void setBookings(List<Booking> bookings) {
		this.bookings = bookings;
	}

}
